apiVersion: troubleshoot.replicated.com/v1beta1
kind: SupportBundle
metadata:
  name: support-sourcegraph
spec:
  collectors:
    - clusterInfo: {}
    - clusterResources: {}
    - logs:
        selector:
          - app=example
          - component=nginx
        namespace: '{{repl Namespace }}'
        limits:
          maxAge: 720h
          maxLines: 10000
