apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: sourcegraph
spec:
  title: Sourcegraph
  icon: https://pbs.twimg.com/profile_images/1428393724527190022/4mt5PACL_400x400.png
  statusInformers:
    - deployment/sourcegraph-frontend
  ports:
    - serviceName: "sourcegraph-frontend"
      servicePort: 3080
      localPort: 8888
      applicationUrl: "http://sourcegraph"
