apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: preflight-sourcegraph
spec:
  analyzers:
    - clusterVersion:
        outcomes:
          - fail:
              when: "< 1.15.0"
              message: The application requires Kubernetes 1.15.0 or later, and recommends 1.17.0.
              uri: https://www.kubernetes.io
          - warn:
              when: "< 1.17.0"
              message: Your cluster meets the minimum version of Kubernetes, but we recommend you update to 1.17.0 or later.
              uri: https://kubernetes.io
          - pass:
              message: Your cluster meets the recommended and required versions of Kubernetes.
    - containerRuntime:
        outcomes:
          - pass:
              when: "== docker"
              message: Docker container runtime was found.
          - pass:
              when: "== containerd"
              message: Containerd container runtime was found.
          - fail:
              message: Did not find Docker container runtime.
    - distribution:
        checkName: Check Kubernetes environment.
        outcomes:
          - fail:
              when: "== docker-desktop"
              message: The application does not support Docker Desktop Clusters
          - fail:
              when: "== microk8s"
              message: The application does not support Microk8s Clusters
          - fail:
              when: "== minikube"
              message: The application does not support Minikube Clusters
          - pass:
              when: "== eks"
              message: EKS is a supported distribution
          - pass:
              when: "== gke"
              message: GKE is a supported distribution
          - pass:
              when: "== aks"
              message: AKS is a supported distribution
          - pass:
              when: "== kurl"
              message: KURL is a supported distribution
          - pass:
              when: "== digitalocean"
              message: DigitalOcean is a supported distribution
          - warn:
              message: Unable to determine the distribution of Kubernetes
    - nodeResources:
        checkName: Total CPU Cores in the cluster is 32 or greater
        outcomes:
          - fail:
              when: "sum(cpuCapacity) < 16"
              message: The cluster must contain at least 16 cores
          - warn:
              when: "sum(cpuCapacity) < 32"
              message: We recommend at least 32 cores
          - pass:
              message: There are at least 32 cores in the cluster
    - nodeResources:
        checkName: Total memory in the cluster must be at least 60Gi
        outcomes:
          - fail:
              when: "sum(memoryCapacity) < 60Gi"
              message: Total amount of memory must be at least 60Gi
          - pass:
              message: Cluster has at least 60Gi of memory
    - nodeResources:
        checkName: Total ephemeral disk size must be at least 100Gi
        outcomes:
          - fail:
              when: "sum(ephemeralStorageCapacity) < 100Gi"
              message: Total amount of ephemeral disk size must be at least 100Gi
          - pass:
              message: Cluster has at least 100Gi of ephemeral disk size
